'use server'

import { db } from '@/lib/db'
import { confirmationRules, interventionRuleVersions, mindRegulationReviews, mindRegulationSessions } from '@/lib/db/schema'
import { getUserId } from '@/lib/user'
import { and, desc, eq } from 'drizzle-orm'
import { revalidatePath } from 'next/cache'
import { z } from 'zod'

const states=['procrastination','drowsiness','restlessness','rumination','balanced'] as const
const checkSchema=z.object({currentState:z.enum(states),energyLevel:z.coerce.number().int().min(1).max(5),agitationLevel:z.coerce.number().int().min(1).max(5),currentTask:z.string().trim().min(1).max(500),triggerText:z.string().trim().max(1000).optional()})
const interventions={procrastination:{type:'right_effort',action:'只做两分钟：打开材料，完成第一个可见动作。'},drowsiness:{type:'tune_mind',action:'先起身、饮水并走动三分钟，再决定是否继续。'},restlessness:{type:'anchor',action:'把注意力放回呼吸与身体，写下唯一下一步。'},rumination:{type:'remove_arrow',action:'分开事实与解释，只处理眼前可改变的一件事。'},balanced:{type:'sixty_seconds',action:'状态可用，保持当前节奏并完成一个专注区块。'}} as const

export async function getMindRegulationDashboard(){const userId=await getUserId();const sessions=await db.select().from(mindRegulationSessions).where(eq(mindRegulationSessions.userId,userId)).orderBy(desc(mindRegulationSessions.createdAt)).limit(30);const reviews=await db.select().from(mindRegulationReviews).where(eq(mindRegulationReviews.userId,userId)).orderBy(desc(mindRegulationReviews.createdAt)).limit(30);return {sessions,reviews,metrics:{checks:sessions.length,completed:sessions.filter(x=>x.actionStatus==='completed').length,helpful:reviews.filter(x=>x.effectiveness==='helpful').length}}}
export async function createMindCheck(input:unknown){const parsed=checkSchema.safeParse(input);if(!parsed.success)return {error:'请完整填写当前状态'};const userId=await getUserId();const intervention=interventions[parsed.data.currentState];const rows=await db.insert(mindRegulationSessions).values({...parsed.data,userId,interventionType:intervention.type,recommendedAction:intervention.action}).returning();revalidatePath('/mind-regulation');return {session:rows[0]}}
export async function acceptMindAction(id:number){const userId=await getUserId();await db.update(mindRegulationSessions).set({actionStatus:'started',selectedAction:'接受建议',startedAt:new Date(),updatedAt:new Date()}).where(and(eq(mindRegulationSessions.id,id),eq(mindRegulationSessions.userId,userId)));revalidatePath('/mind-regulation');return {ok:true as const}}
const reviewSchema=z.object({sessionId:z.coerce.number().int().positive(),actualResult:z.string().trim().min(1).max(2000),stateAfter:z.enum(states),effectiveness:z.enum(['helpful','neutral','unhelpful']),lessonText:z.string().trim().max(2000).optional(),convertToRule:z.boolean().default(false)})
export async function reviewMindAction(input:unknown){const parsed=reviewSchema.safeParse(input);if(!parsed.success)return {error:'请完整填写复盘结果'};const userId=await getUserId();const source=await db.select().from(mindRegulationSessions).where(and(eq(mindRegulationSessions.id,parsed.data.sessionId),eq(mindRegulationSessions.userId,userId))).limit(1);if(!source[0])return {error:'记录不存在'};const exists=await db.select().from(mindRegulationReviews).where(and(eq(mindRegulationReviews.sessionId,parsed.data.sessionId),eq(mindRegulationReviews.userId,userId))).limit(1);if(exists[0])return {error:'此行动已经复盘'};await db.transaction(async tx=>{await tx.insert(mindRegulationReviews).values({...parsed.data,userId});await tx.update(mindRegulationSessions).set({actionStatus:'completed',completedAt:new Date(),updatedAt:new Date()}).where(and(eq(mindRegulationSessions.id,parsed.data.sessionId),eq(mindRegulationSessions.userId,userId)));if(parsed.data.convertToRule&&parsed.data.lessonText){const rows=await tx.insert(confirmationRules).values({userId,domain:'mind',scenario:source[0].currentState,ruleText:parsed.data.lessonText,status:'draft',triggerText:source[0].triggerText??source[0].currentTask,recommendedAction:source[0].recommendedAction,sourceType:'mind_review'}).returning();await tx.insert(interventionRuleVersions).values({userId,ruleId:rows[0].id,version:1,sceneTagsSnapshot:source[0].currentState,triggerTextSnapshot:source[0].triggerText??source[0].currentTask,actionSnapshot:source[0].recommendedAction,severitySnapshot:'medium',changeReason:'心念调伏复盘生成草稿'})}});revalidatePath('/mind-regulation');revalidatePath('/rules');return {ok:true as const}}
