"use server"

import { z } from "zod"
import { and, desc, eq } from "drizzle-orm"
import { revalidatePath } from "next/cache"
import { db } from "@/lib/db"
import { getUserId } from "@/lib/user"
import { relationships, relationshipEmotionalStates, relationshipSignals, relationshipStageSnapshots, relationshipCommunicationPlans, relationshipInteractionOutcomes, relationshipResourceAssessments, resources } from "@/lib/db/schema"
import { assessCommunicationRisk, assessRelationshipResource, canTransitionPlan, suggestRelationshipStage, type PlanStatus } from "@/lib/relationship-stage-rules"

const idSchema = z.coerce.number().int().positive()
const ownedRelationship = async (id: number, userId: string) => (await db.select().from(relationships).where(and(eq(relationships.id, id), eq(relationships.userId, userId))).limit(1))[0]
const fail = (error: unknown) => ({ error: error instanceof z.ZodError ? error.issues[0]?.message ?? "输入无效" : error instanceof Error ? error.message : "操作失败" })

export async function getRelationshipStageData(relationshipId: number) {
  const userId = await getUserId(); if (!await ownedRelationship(relationshipId, userId)) return null
  const [emotions, signals, stages, plans, outcomes, resourceAssessments, relationshipResources] = await Promise.all([
    db.select().from(relationshipEmotionalStates).where(and(eq(relationshipEmotionalStates.userId,userId),eq(relationshipEmotionalStates.relationshipId,relationshipId))).orderBy(desc(relationshipEmotionalStates.createdAt)).limit(20),
    db.select().from(relationshipSignals).where(and(eq(relationshipSignals.userId,userId),eq(relationshipSignals.relationshipId,relationshipId))).orderBy(desc(relationshipSignals.createdAt)).limit(100),
    db.select().from(relationshipStageSnapshots).where(and(eq(relationshipStageSnapshots.userId,userId),eq(relationshipStageSnapshots.relationshipId,relationshipId))).orderBy(desc(relationshipStageSnapshots.createdAt)).limit(20),
    db.select().from(relationshipCommunicationPlans).where(and(eq(relationshipCommunicationPlans.userId,userId),eq(relationshipCommunicationPlans.relationshipId,relationshipId))).orderBy(desc(relationshipCommunicationPlans.createdAt)).limit(30),
    db.select().from(relationshipInteractionOutcomes).where(and(eq(relationshipInteractionOutcomes.userId,userId),eq(relationshipInteractionOutcomes.relationshipId,relationshipId))).orderBy(desc(relationshipInteractionOutcomes.createdAt)).limit(30),
    db.select().from(relationshipResourceAssessments).where(and(eq(relationshipResourceAssessments.userId,userId),eq(relationshipResourceAssessments.relationshipId,relationshipId))).orderBy(desc(relationshipResourceAssessments.createdAt)).limit(30),
    db.select().from(resources).where(and(eq(resources.userId,userId),eq(resources.domain,"relationship"))).orderBy(desc(resources.updatedAt)).limit(50),
  ])
  return { emotions, signals, stages, plans, outcomes, resourceAssessments, resources: relationshipResources, suggestion: suggestRelationshipStage(signals) }
}

export async function saveRelationshipEmotion(input: unknown) { try { const data=z.object({relationshipId:idSchema,emotion:z.string().trim().min(1).max(60),intensity:z.coerce.number().int().min(0).max(10),trigger:z.string().trim().max(500).optional(),bodyResponse:z.string().trim().max(300).optional(),impulse:z.string().trim().max(300).optional(),currentNeed:z.string().trim().max(300).optional(),actionReadiness:z.enum(["ready","cautious","not_ready"])}).parse(input); const userId=await getUserId(); if(!await ownedRelationship(data.relationshipId,userId)) return {error:"关系不存在"}; await db.insert(relationshipEmotionalStates).values({...data,userId}); revalidatePath(`/relationships/${data.relationshipId}`); return {ok:true} } catch(e){return fail(e)} }

export async function saveRelationshipSignal(input: unknown) { try { const data=z.object({relationshipId:idSchema,signalKind:z.enum(["fact","inference","question"]),direction:z.enum(["positive","neutral","risk","boundary"]),strength:z.coerce.number().int().min(1).max(5),content:z.string().trim().min(2).max(1000),source:z.string().trim().max(300).optional(),verificationStatus:z.enum(["unverified","verified","rejected"])}).parse(input); const userId=await getUserId(); if(!await ownedRelationship(data.relationshipId,userId)) return {error:"关系不存在"}; await db.insert(relationshipSignals).values({...data,userId,verifiedAt:data.verificationStatus==="verified"?new Date():null}); revalidatePath(`/relationships/${data.relationshipId}`); return {ok:true} } catch(e){return fail(e)} }

export async function confirmRelationshipStage(input: unknown) { try { const data=z.object({relationshipId:idSchema,confirmedStage:z.enum(["initial_contact","getting_to_know","stable_contact","mutual_trust","boundary_review"])}).parse(input); const userId=await getUserId(); const relationship=await ownedRelationship(data.relationshipId,userId); if(!relationship)return {error:"关系不存在"}; const signals=await db.select().from(relationshipSignals).where(and(eq(relationshipSignals.userId,userId),eq(relationshipSignals.relationshipId,data.relationshipId))).limit(100); const result=suggestRelationshipStage(signals); await db.transaction(async tx=>{await tx.insert(relationshipStageSnapshots).values({userId,relationshipId:data.relationshipId,suggestedStage:result.suggestedStage,confirmedStage:data.confirmedStage,confidence:result.confidence,supportingSignalIds:JSON.stringify(result.supportingSignalIds),counterSignalIds:JSON.stringify(result.counterSignalIds),rationale:result.rationale,confirmedByUser:true}); await tx.update(relationships).set({currentStage:data.confirmedStage,stageConfidence:result.confidence,stageRationale:result.rationale,stageConfirmedAt:new Date(),updatedAt:new Date()}).where(and(eq(relationships.id,data.relationshipId),eq(relationships.userId,userId)))}); revalidatePath(`/relationships/${data.relationshipId}`); return {ok:true} } catch(e){return fail(e)} }

export async function createCommunicationPlan(input: unknown) { try { const data=z.object({relationshipId:idSchema,goal:z.string().trim().min(2).max(500),minimalRequest:z.string().trim().min(2).max(500),boundary:z.string().trim().min(2).max(500),avoidTopics:z.string().trim().max(500).optional(),channel:z.enum(["in_person","message","call","email"]),plannedAt:z.coerce.date().optional()}).parse(input); const userId=await getUserId(); if(!await ownedRelationship(data.relationshipId,userId))return {error:"关系不存在"}; const [emotion]=await db.select().from(relationshipEmotionalStates).where(and(eq(relationshipEmotionalStates.userId,userId),eq(relationshipEmotionalStates.relationshipId,data.relationshipId))).orderBy(desc(relationshipEmotionalStates.createdAt)).limit(1); const signals=await db.select().from(relationshipSignals).where(and(eq(relationshipSignals.userId,userId),eq(relationshipSignals.relationshipId,data.relationshipId))).limit(100); const risk=assessCommunicationRisk({intensity:emotion?.intensity,actionReadiness:emotion?.actionReadiness,signals}); const [created]=await db.insert(relationshipCommunicationPlans).values({...data,userId,riskLevel:risk.riskLevel,preflightChecklist:`确认目标不是索取确定性\n只提出一个最小请求\n尊重对方拒绝或延迟回应\n${risk.reason}`,status:"draft"}).returning({id:relationshipCommunicationPlans.id}); revalidatePath(`/relationships/${data.relationshipId}`); return {ok:true,id:created.id,risk} } catch(e){return fail(e)} }

export async function transitionCommunicationPlan(input: unknown) { try { const data=z.object({planId:idSchema,to:z.enum(["ready","sent","cancelled","expired"])}).parse(input); const userId=await getUserId(); const [plan]=await db.select().from(relationshipCommunicationPlans).where(and(eq(relationshipCommunicationPlans.id,data.planId),eq(relationshipCommunicationPlans.userId,userId))).limit(1); if(!plan)return {error:"计划不存在"}; if(!canTransitionPlan(plan.status as PlanStatus,data.to))return {error:"非法计划状态转换"}; if(data.to==="ready"&&plan.riskLevel==="high")return {error:"高风险状态不能进入待发送，请先降低情绪强度或补足边界。"}; await db.update(relationshipCommunicationPlans).set({status:data.to,sentAt:data.to==="sent"?new Date():plan.sentAt,updatedAt:new Date()}).where(and(eq(relationshipCommunicationPlans.id,data.planId),eq(relationshipCommunicationPlans.userId,userId))); revalidatePath(`/relationships/${plan.relationshipId}`); return {ok:true} } catch(e){return fail(e)} }

export async function saveInteractionOutcome(input: unknown) { try { const data=z.object({planId:idSchema,whatHappened:z.string().trim().min(2).max(2000),responseObserved:z.string().trim().min(2).max(1000),energyAfter:z.enum(["supported","calm","drained","confused","anxious"]),boundaryResult:z.enum(["held","partly_held","crossed"]),mainlineImpact:z.string().trim().max(500).optional(),nextStep:z.string().trim().max(500).optional(),needsAshReview:z.boolean()}).parse(input); const userId=await getUserId(); const [plan]=await db.select().from(relationshipCommunicationPlans).where(and(eq(relationshipCommunicationPlans.id,data.planId),eq(relationshipCommunicationPlans.userId,userId))).limit(1); if(!plan)return {error:"计划不存在"}; if(plan.status!=="sent")return {error:"只有已发送/已执行的计划才能复盘"}; await db.transaction(async tx=>{await tx.insert(relationshipInteractionOutcomes).values({...data,userId,relationshipId:plan.relationshipId}); await tx.update(relationshipCommunicationPlans).set({status:"reviewed",updatedAt:new Date()}).where(and(eq(relationshipCommunicationPlans.id,plan.id),eq(relationshipCommunicationPlans.userId,userId)))}); revalidatePath(`/relationships/${plan.relationshipId}`); return {ok:true} } catch(e){return fail(e)} }

export async function assessRelationshipLearningResource(input: unknown) { try { const data=z.object({relationshipId:idSchema,resourceId:idSchema,credibility:z.coerce.number().int().min(0).max(10),manipulationRisk:z.coerce.number().int().min(0).max(10),stigmaRisk:z.coerce.number().int().min(0).max(10),absolutismRisk:z.coerce.number().int().min(0).max(10),applicableBoundary:z.string().trim().min(2).max(1000),actionablePrinciple:z.string().trim().min(2).max(1000)}).parse(input); const userId=await getUserId(); if(!await ownedRelationship(data.relationshipId,userId))return {error:"关系不存在"}; const [resource]=await db.select().from(resources).where(and(eq(resources.id,data.resourceId),eq(resources.userId,userId))).limit(1); if(!resource)return {error:"资源不存在"}; const status=assessRelationshipResource(data); await db.insert(relationshipResourceAssessments).values({...data,userId,status}).onConflictDoUpdate({target:[relationshipResourceAssessments.userId,relationshipResourceAssessments.relationshipId,relationshipResourceAssessments.resourceId],set:{...data,status}}); revalidatePath(`/relationships/${data.relationshipId}`); return {ok:true,status} } catch(e){return fail(e)} }

export async function initializeThaiJuniorRelationship() { try { const userId=await getUserId(); const seedKey="thai-junior-v1"; const [existing]=await db.select().from(relationships).where(and(eq(relationships.userId,userId),eq(relationships.seedKey,seedKey))).limit(1); if(existing)return {ok:true,id:existing.id,existing:true}; const [created]=await db.transaction(async tx=>{const [relationship]=await tx.insert(relationships).values({userId,personName:"泰语系学妹",relationshipType:"classmate",relationshipStatus:"observe_carefully",currentStage:"initial_contact",knownFacts:"对方是泰语系学妹。",unverifiedHypotheses:"对方可能愿意进一步了解；当前关系意愿和节奏尚不明确。",openQuestions:"对方是否愿意保持稳定交流？什么沟通频率让双方都舒适？",currentContext:"谨慎观察，以真实互动信号更新判断。",nextAction:"observe",seedKey}).returning(); await tx.insert(relationshipSignals).values([{userId,relationshipId:relationship.id,signalKind:"fact",direction:"neutral",strength:2,content:"对方是泰语系学妹。",source:"用户提供的背景资料",verificationStatus:"verified",verifiedAt:new Date(),seedKey:"thai-junior-fact-v1"},{userId,relationshipId:relationship.id,signalKind:"question",direction:"neutral",strength:2,content:"对方是否愿意保持稳定交流？",source:"待验证问题",verificationStatus:"unverified",seedKey:"thai-junior-question-v1"}]); return [relationship]}); revalidatePath("/relationships"); return {ok:true,id:created.id,existing:false} } catch(e){return fail(e)} }
