"use client"

import { useState, useTransition } from "react"
import { useRouter } from "next/navigation"
import { Archive, ClipboardCheck, Play, Square, X } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { abandonEntertainmentSession, assessEntertainmentSession, endEntertainmentSession, saveEntertainmentReflection, startEntertainmentSession } from "@/app/actions/entertainment"
import { ENTERTAINMENT_TYPES } from "@/lib/entertainment-rules"

function ErrorMessage({ value }: { value: string | null }) { return value ? <p role="alert" className="rounded-lg border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive">{value}</p> : null }
const text = (form: FormData, name: string) => String(form.get(name) || "")

export function StartEntertainmentForm() {
  const router = useRouter(); const [pending, startTransition] = useTransition(); const [error, setError] = useState<string | null>(null)
  const [type, setType] = useState<(typeof ENTERTAINMENT_TYPES)[number][0]>("video")
  return <form className="flex flex-col gap-4" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); setError(null); startTransition(async () => {
    const result = await startEntertainmentSession({ title: text(form,"title"), entertainmentType:type, plannedMinutes:form.get("plannedMinutes"), plannedBudgetCny:form.get("plannedBudgetCny"), boundaryNote:text(form,"boundaryNote"), preState:text(form,"preState"), purpose:text(form,"purpose"), mainline:text(form,"mainline"), plannedQuantity:form.get("plannedQuantity") || undefined, quantityUnit:text(form,"quantityUnit"), latestEndAt:form.get("latestEndAt"), nextAction:text(form,"nextAction") })
    if ("error" in result) setError(result.error || "操作失败，请重试"); else router.push(`/entertainment/${result.id}`)
  }) }}>
    <Field id="ent-title" name="title" label="这次想做什么?" placeholder="例如：看两集纪录片" required />
    <fieldset className="flex flex-col gap-2"><legend className="text-sm font-medium">娱乐类型</legend><div className="flex flex-wrap gap-2">{ENTERTAINMENT_TYPES.map(([value,label])=><Button key={value} type="button" variant={type===value?"default":"outline"} aria-pressed={type===value} onClick={()=>setType(value)}>{label}</Button>)}</div></fieldset>
    <div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><Field id="pre-state" name="preState" label="开始前状态" placeholder="疲惫、焦虑、正常…" required /><Field id="purpose" name="purpose" label="娱乐目的" placeholder="恢复注意力，而不是逃避任务" required /></div>
    <Field id="mainline" name="mainline" label="当前服务的主线" placeholder="例如：休息后继续完成课程作业" required />
    <div className="grid grid-cols-2 gap-3"><NumberField id="ent-minutes" name="plannedMinutes" label="计划时长(分钟)" defaultValue={45} max={1440}/><NumberField id="ent-budget" name="plannedBudgetCny" label="预算上限(元)" defaultValue={0} max={1000000}/></div>
    <div className="grid grid-cols-2 gap-3"><NumberField id="ent-quantity" name="plannedQuantity" label="计划数量" defaultValue={1} max={100}/><Field id="quantity-unit" name="quantityUnit" label="数量单位" placeholder="集 / 局 / 章" /></div>
    <div className="flex flex-col gap-1.5"><Label htmlFor="latest-end">最晚结束时间</Label><Input id="latest-end" name="latestEndAt" type="datetime-local" required /></div>
    <Field id="next-action" name="nextAction" label="结束后的唯一动作" placeholder="洗漱并完成 10 分钟主线任务" required />
    <div className="flex flex-col gap-1.5"><Label htmlFor="ent-boundary">停止边界(可选)</Label><Textarea id="ent-boundary" name="boundaryNote" maxLength={500} placeholder="不自动续播、不追加付费" /></div>
    <ErrorMessage value={error}/><Button type="submit" size="lg" disabled={pending}><Play />{pending?"开始中…":"生成执行计划并开始"}</Button>
  </form>
}

export function ActiveSessionActions({ sessionId }: { sessionId:number }) { const router=useRouter(); const [pending,startTransition]=useTransition(); const [error,setError]=useState<string|null>(null); const run=(action:"end"|"abandon")=>startTransition(async()=>{const result=action==="end"?await endEntertainmentSession(sessionId):await abandonEntertainmentSession(sessionId); if("error" in result)setError(result.error||"操作失败");else if(action==="abandon")router.push("/entertainment");else router.refresh()}); return <div className="flex flex-col gap-3"><ErrorMessage value={error}/><div className="flex gap-2"><Button className="flex-1" size="lg" disabled={pending} onClick={()=>run("end")}><Square/>结束并评估</Button><Button variant="outline" size="lg" disabled={pending} onClick={()=>run("abandon")}><X/>放弃会话</Button></div></div> }

export function EntertainmentAssessmentForm({ sessionId, plannedMinutes, plannedBudgetCny }: { sessionId:number; plannedMinutes:number; plannedBudgetCny:number }) {
  const router=useRouter(); const [pending,startTransition]=useTransition(); const [error,setError]=useState<string|null>(null); const [toggles,setToggles]=useState({stop:true,budget:true,delayed:false,autoplay:false,next:false})
  const toggle=(key:keyof typeof toggles)=><Toggle value={toggles[key]} onChange={(value)=>setToggles((old)=>({...old,[key]:value}))} label={({stop:"按时停止",budget:"预算内完成",delayed:"影响了主线任务",autoplay:"发生自动续播",next:"已启动结束后动作"})[key]} danger={key==="delayed"||key==="autoplay"}/>
  return <form className="flex flex-col gap-4" onSubmit={(event)=>{event.preventDefault();const form=new FormData(event.currentTarget);setError(null);startTransition(async()=>{const result=await assessEntertainmentSession({sessionId,actualMinutes:form.get("actualMinutes"),actualCostCny:form.get("actualCostCny"),recoveredEnergy:form.get("recoveredEnergy"),emotionAfter:form.get("emotionAfter"),regretLevel:form.get("regretLevel"),didStopOnTime:toggles.stop,didStayInBudget:toggles.budget,delayedMainline:toggles.delayed,actualGain:text(form,"actualGain"),nextRecoveryAction:text(form,"nextRecoveryAction"),actualQuantity:form.get("actualQuantity")||undefined,autoplayOccurred:toggles.autoplay,learningScore:form.get("learningScore"),learningSummary:text(form,"learningSummary"),learningApplication:text(form,"learningApplication"),stateChange:text(form,"stateChange"),stopDifficulty:form.get("stopDifficulty"),contentSatisfaction:form.get("contentSatisfaction"),timeSatisfaction:form.get("timeSatisfaction"),stopSatisfaction:form.get("stopSatisfaction"),stateSatisfaction:form.get("stateSatisfaction"),decisionSatisfaction:form.get("decisionSatisfaction"),mainlineHelpScore:form.get("mainlineHelpScore"),nextActionStarted:toggles.next,nextActionStartedAt:form.get("nextActionStartedAt")||undefined,nextActionType:text(form,"nextActionType"),nextActionEvidence:text(form,"nextActionEvidence"),stopDifficultyReason:text(form,"stopDifficultyReason"),rationalization:text(form,"rationalization"),sleepImpact:text(form,"sleepImpact"),nextDayImpact:text(form,"nextDayImpact"),satisfiedPart:text(form,"satisfiedPart"),unsatisfiedPart:text(form,"unsatisfiedPart"),mainlineResult:text(form,"mainlineResult")});if("error" in result)setError(result.error||"操作失败");else router.refresh()})}}>
    <div className="grid grid-cols-2 gap-3"><NumberField id="actual-minutes" name="actualMinutes" label="实际时长(分钟)" defaultValue={plannedMinutes} max={2880}/><NumberField id="actual-cost" name="actualCostCny" label="实际花费(元)" defaultValue={plannedBudgetCny} max={1000000}/></div>
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-3"><NumberField id="actual-quantity" name="actualQuantity" label="实际数量" defaultValue={1} max={1000}/><NumberField id="energy" name="recoveredEnergy" label="恢复感 0–10" defaultValue={5} max={10}/><NumberField id="emotion" name="emotionAfter" label="结束情绪 0–10" defaultValue={5} max={10}/><NumberField id="regret" name="regretLevel" label="后悔度 0–10" defaultValue={0} max={10}/><NumberField id="stop-difficulty" name="stopDifficulty" label="停止难度 0–10" defaultValue={3} max={10}/><NumberField id="learning-score" name="learningScore" label="学习收获 0–10" defaultValue={0} max={10}/></div>
    <div className="flex flex-col gap-2">{toggle("stop")}{toggle("budget")}{toggle("autoplay")}{toggle("delayed")}{toggle("next")}</div>
    <section className="flex flex-col gap-3 rounded-lg border p-3"><p className="text-sm font-medium">五项满意度 0–10</p><div className="grid grid-cols-2 gap-3 sm:grid-cols-5">{[["contentSatisfaction","内容"],["timeSatisfaction","时间"],["stopSatisfaction","停止"],["stateSatisfaction","状态"],["decisionSatisfaction","决策"]].map(([name,label])=><NumberField key={name} id={name} name={name} label={label} defaultValue={5} max={10}/>)}</div><NumberField id="mainlineHelpScore" name="mainlineHelpScore" label="主线帮助度 -5 至 +5" defaultValue={0} min={-5} max={5}/></section>
    <TextAreaField id="actual-gain" name="actualGain" label="实际获得了什么?"/><TextAreaField id="learning-summary" name="learningSummary" label="学习收获与证据"/><TextAreaField id="state-change" name="stateChange" label="娱乐前后状态变化"/><TextAreaField id="stop-reason" name="stopDifficultyReason" label="停止困难原因"/><TextAreaField id="rationalization" name="rationalization" label="当时的合理化理由"/><TextAreaField id="sleep-impact" name="sleepImpact" label="睡眠影响（如：转入睡眠）"/><TextAreaField id="next-day-impact" name="nextDayImpact" label="第二天影响"/>
    <div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><Field id="next-action-type" name="nextActionType" label="下一动作类型"/><Field id="next-action-evidence" name="nextActionEvidence" label="下一动作证据"/></div>{toggles.next&&<div className="flex flex-col gap-1.5"><Label htmlFor="next-action-at">下一动作启动时间</Label><Input id="next-action-at" name="nextActionStartedAt" type="datetime-local"/></div>}
    <TextAreaField id="satisfied" name="satisfiedPart" label="满意的部分"/><TextAreaField id="unsatisfied" name="unsatisfiedPart" label="不满意的部分"/><TextAreaField id="mainline-result" name="mainlineResult" label="对主线的实际结果"/><Field id="recovery-action" name="nextRecoveryAction" label="下一步恢复动作"/>
    <ErrorMessage value={error}/><Button type="submit" size="lg" disabled={pending}><ClipboardCheck/>{pending?"评估中…":"提交五维结果"}</Button>
  </form>
}

export function EntertainmentReflectionForm({ sessionId, defaultFact, defaultLesson, defaultRule }: { sessionId:number; defaultFact:string; defaultLesson:string; defaultRule:string }) { const router=useRouter();const[pending,startTransition]=useTransition();const[error,setError]=useState<string|null>(null);const[ash,setAsh]=useState(true);const[rule,setRule]=useState(false);return <form className="flex flex-col gap-4" onSubmit={(event)=>{event.preventDefault();const form=new FormData(event.currentTarget);setError(null);startTransition(async()=>{const result=await saveEntertainmentReflection({sessionId,factSummary:text(form,"factSummary"),trigger:text(form,"trigger"),lesson:text(form,"lesson"),principle:text(form,"principle"),candidateRule:text(form,"candidateRule"),saveToAsh:ash,saveToRuleLibrary:rule,gptReviewResult:text(form,"gptReviewResult"),gptResultStatus:text(form,"gptResultStatus") as "agreed"|"partially_agreed"|"disagreed",gptConversationUrl:text(form,"gptConversationUrl"),gptSummary:text(form,"gptSummary"),gptClassification:text(form,"gptClassification"),lossOfControlPoint:text(form,"lossOfControlPoint"),identifiedRealNeed:text(form,"identifiedRealNeed"),userConfirmedInsight:text(form,"userConfirmedInsight"),nextMinimalAdjustment:text(form,"nextMinimalAdjustment")});if("error" in result)setError(result.error||"操作失败");else router.refresh()})}}>
    <TextAreaField id="gpt-result" name="gptReviewResult" label="GPT 分析回填 *" required/><div className="flex flex-col gap-1.5"><Label htmlFor="gpt-status">你对 GPT 分析的态度 *</Label><select id="gpt-status" name="gptResultStatus" required className="min-h-11 rounded-lg border bg-background px-3 text-sm"><option value="">请选择</option><option value="agreed">同意</option><option value="partially_agreed">部分同意</option><option value="disagreed">不同意</option></select></div><Field id="gpt-url" name="gptConversationUrl" label="GPT 会话链接" type="url"/><TextAreaField id="gpt-summary" name="gptSummary" label="GPT 摘要"/><TextAreaField id="gpt-classification" name="gptClassification" label="GPT 判断分类"/><TextAreaField id="loss-point" name="lossOfControlPoint" label="失控节点"/><TextAreaField id="real-need" name="identifiedRealNeed" label="识别出的真实需求"/><TextAreaField id="confirmed-insight" name="userConfirmedInsight" label="我确认的新认识"/><TextAreaField id="minimal-adjustment" name="nextMinimalAdjustment" label="下一次最小调整"/>
    <TextAreaField id="fact-summary" name="factSummary" label="事实摘要 *" defaultValue={defaultFact} required/><TextAreaField id="trigger" name="trigger" label="触发因素"/><TextAreaField id="lesson" name="lesson" label="候选教训 *" defaultValue={defaultLesson} required/><TextAreaField id="principle" name="principle" label="候选原则"/><TextAreaField id="candidate-rule" name="candidateRule" label="候选拦截规则" defaultValue={defaultRule}/>
    <div className="flex flex-col gap-2"><Toggle value={ash} onChange={setAsh} label="确认写入灰烬备忘录"/><Toggle value={rule} onChange={setRule} label="确认写入规则库(默认关闭)"/></div><p className="text-xs leading-relaxed text-muted-foreground">先确认你对 GPT 分析的态度。不同意时只保留本次记录，不污染灰烬和规则库。</p><ErrorMessage value={error}/><Button type="submit" size="lg" disabled={pending}><Archive/>{pending?"沉淀中…":"确认并生成 Markdown"}</Button>
  </form> }

function Field({id,name,label,placeholder,type="text",required=false}:{id:string;name:string;label:string;placeholder?:string;type?:string;required?:boolean}){return <div className="flex flex-col gap-1.5"><Label htmlFor={id}>{label}</Label><Input id={id} name={name} type={type} placeholder={placeholder} required={required} maxLength={500}/></div>}
function NumberField({id,name,label,defaultValue,min=0,max}:{id:string;name:string;label:string;defaultValue:number;min?:number;max:number}){return <div className="flex flex-col gap-1.5"><Label htmlFor={id}>{label}</Label><Input id={id} name={name} type="number" inputMode="numeric" min={min} max={max} defaultValue={defaultValue} required/></div>}
function Toggle({value,onChange,label,danger=false}:{value:boolean;onChange:(value:boolean)=>void;label:string;danger?:boolean}){return <button type="button" aria-pressed={value} onClick={()=>onChange(!value)} className={`flex min-h-11 items-center justify-between rounded-lg border px-3 text-sm ${value?(danger?"border-destructive/40 bg-destructive/5 text-destructive":"border-primary bg-primary/5 text-foreground"):"border-border bg-card text-muted-foreground"}`}><span>{label}</span><span>{value?"是":"否"}</span></button>}
function TextAreaField({id,name,label,defaultValue,required=false}:{id:string;name:string;label:string;defaultValue?:string;required?:boolean}){return <div className="flex flex-col gap-1.5"><Label htmlFor={id}>{label}</Label><Textarea id={id} name={name} defaultValue={defaultValue} required={required} maxLength={12000}/></div>}
